text = input("Enter some text :")
print("Before >>>>>", text)
text = text.lower()
text = text.replace("a","4")
text = text.replace("b","8")
text = text.replace("e","3")
text = text.replace("l","1")
text = text.replace("o","0")
text = text.replace("s","5")
text = text.replace("t","7")
print("After >>>>>",text)